### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [1]:
import pandas as pd

df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [2]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [3]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [11]:
df['color'] = encoder.fit_transform(df[['color']])

c:\Users\Sara Shaik\anaconda3\envs\feature-engineering\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [12]:
encoder.classes_

array(['blue', 'green', 'red'], dtype=object)

In [13]:
df.head()

   color
0      2
1      0
2      1
3      1
4      2

### Ordinal Encoding
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [23]:
from sklearn.preprocessing import OrdinalEncoder

In [24]:
df = pd.DataFrame({
    'size': ['small','medium','small','large','small','medium','medium','medium','large']
})

In [27]:
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [28]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.]])

In [29]:
encoder.categories_

[array(['small', 'medium', 'large'], dtype=object)]

In [34]:
encoder.transform([['large'],['small'],['medium']])

c:\Users\Sara Shaik\anaconda3\envs\feature-engineering\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.],
       [0.],
       [1.]])